[profile.default]
solc_version = '0.8.28'
optimizer = true
optimizer-runs = 200
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./test/bin" }]

[fuzz]
runs = 5000
max_test_rejects = 150000
